# Generated by Django 5.2.10 on 2026-02-05 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0004_alter_contracts_regex"),
        ("corporate", "0010_alter_bank_bik"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manual",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "dt",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=12, verbose_name="Дт"
                    ),
                ),
                (
                    "cr",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=12, verbose_name="Кт"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("RUB", "RUB"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                            ("CHF", "CHF"),
                            ("JPY", "JPY"),
                            ("CNY", "CNY"),
                            ("CAD", "CAD"),
                            ("AUD", "AUD"),
                            ("HKD", "HKD"),
                            ("KZT", "KZT"),
                            ("KGS", "KGS"),
                            ("UZS", "UZS"),
                            ("AZN", "AZN"),
                            ("AMD", "AMD"),
                            ("AED", "AED"),
                        ],
                        default="RUB",
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                ("temp", models.TextField(verbose_name="Описание операции")),
                (
                    "acc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corporate.coa",
                        verbose_name="Счет",
                    ),
                ),
                (
                    "cfitem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corporate.cfitems",
                        verbose_name="Статья CF",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contracts.contracts",
                        verbose_name="Договор",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corporate.owners",
                        verbose_name="Компания",
                    ),
                ),
                (
                    "pid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pid_manual",
                        to="grossbook.manual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проводка",
                "verbose_name_plural": "Ручные проводки",
            },
        ),
    ]
