# Generated by Django 5.2.10 on 2026-03-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grossbook", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settlements",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("date_from", models.DateField(verbose_name="Дата")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "dt",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Дт"
                    ),
                ),
                (
                    "cr",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Кр"
                    ),
                ),
            ],
            options={
                "verbose_name": "Взаиморасчеты",
                "verbose_name_plural": "Взаиморасчеты",
                "db_table": '"gl"."mv_accurals"',
                "managed": False,
            },
        ),
    ]
