# Generated by Django 5.2.10 on 2026-03-13 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grossbook", "0002_settlements"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Settlements",
        ),
    ]
