# Generated by Django 5.2.10 on 2026-07-30 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0020_alter_accuralfn_options_alter_contracts_bs_and_more'),
        ('grossbook', '0003_delete_settlements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAdjustment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('adjustment_date', models.DateField(db_index=True, verbose_name='Дата корректировки')),
                ('principal_balance', models.DecimalField(decimal_places=2, help_text='Сумма в валюте договора, не в копейках.', max_digits=18, verbose_name='Остаток тела после корректировки')),
                ('interest_balance', models.DecimalField(decimal_places=2, default=0, help_text='Сумма в валюте договора, не в копейках.', max_digits=18, verbose_name='Остаток процентов после корректировки')),
                ('reason', models.CharField(choices=[('repayment_reallocation', 'Исправление распределения платежа'), ('opening_balance', 'Корректировка начального остатка'), ('accounting_reconciliation', 'Корректировка по результатам сверки'), ('other', 'Другое')], default='accounting_reconciliation', max_length=40, verbose_name='Причина')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Учитывать в расчёте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_adjustments', to='contracts.contracts', verbose_name='Договор')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loan_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Корректировка займа',
                'verbose_name_plural': 'Корректировки займов',
                'db_table': 'grossbook_loanadjustment',
                'ordering': ('-adjustment_date', '-id'),
                'indexes': [models.Index(fields=['contract', 'adjustment_date', 'is_active'], name='loan_adj_contract_date_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('contract', 'adjustment_date'), name='uniq_active_loan_adjustment_contract_date'), models.CheckConstraint(condition=models.Q(('principal_balance__gte', 0)), name='loan_adjustment_principal_nonnegative'), models.CheckConstraint(condition=models.Q(('interest_balance__gte', 0)), name='loan_adjustment_interest_nonnegative')],
            },
        ),
    ]
