# Generated by Django 5.2.10 on 2026-03-28 12:54

import budget.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0020_alter_accuralfn_options_alter_contracts_bs_and_more"),
        ("corporate", "0016_coafn_conditionscoa"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="Версия бюджета"
                    ),
                ),
                (
                    "budget_type",
                    models.CharField(
                        choices=[
                            ("baseline", "Базовый план"),
                            ("rolling", "Текущий прогноз"),
                            ("adhoc", "Ad-hoc"),
                        ],
                        default="baseline",
                        max_length=20,
                        verbose_name="Тип бюджета",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("date_from", models.DateField(verbose_name="Дата начала")),
                ("date_to", models.DateField(verbose_name="Дата окончания")),
                (
                    "revenue_param",
                    models.JSONField(
                        default=budget.models.revenue_json,
                        verbose_name="Параметры доходной части",
                    ),
                ),
                (
                    "wb_costs_params",
                    models.JSONField(
                        default=budget.models.wbcost_json,
                        verbose_name="Параметры расходной части WB",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия бюджета",
                "verbose_name_plural": "Версии бюджетов",
                "ordering": ["-date_from", "number"],
            },
        ),
        migrations.CreateModel(
            name="Gl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("dt", models.BigIntegerField(default=0, verbose_name="Дебет, коп.")),
                ("cr", models.BigIntegerField(default=0, verbose_name="Кредит, коп.")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Описание"
                    ),
                ),
                (
                    "chapter",
                    models.CharField(blank=True, max_length=500, verbose_name="Раздел"),
                ),
                (
                    "acc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gl_entries",
                        to="corporate.coa",
                        verbose_name="Счет",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gl_entries",
                        to="contracts.contracts",
                        verbose_name="Договор",
                    ),
                ),
                (
                    "subconto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gl_entries",
                        to="corporate.cfitems",
                        verbose_name="Субконто",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gl_entries",
                        to="budget.budgetversion",
                        verbose_name="Версия бюджета",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проводка GL",
                "verbose_name_plural": "Проводки GL",
                "ordering": ["date", "id"],
                "indexes": [
                    models.Index(
                        fields=["version", "date"], name="budget_gl_version_14b545_idx"
                    ),
                    models.Index(fields=["acc"], name="budget_gl_acc_id_40b89d_idx"),
                    models.Index(
                        fields=["contract"], name="budget_gl_contrac_117efb_idx"
                    ),
                    models.Index(
                        fields=["subconto"], name="budget_gl_subcont_774e6d_idx"
                    ),
                ],
            },
        ),
    ]
