# Generated by Django 5.2.10 on 2026-03-31 12:31

import budget.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetversion",
            name="cf_params",
            field=models.JSONField(
                default=budget.models.cf_json, verbose_name="Параметры планирования CF"
            ),
        ),
    ]
