# Generated by Django 5.2.10 on 2026-03-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0002_budgetversion_cf_params"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetversion",
            name="report",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Отчет по бюджету"
            ),
        ),
    ]
