# Generated by Django 5.2.10 on 2026-04-03 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_budgetversion_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetversion',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения'),
        ),
        migrations.AddField(
            model_name='budgetversion',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budget_versions', to=settings.AUTH_USER_MODEL, verbose_name='Утвердил'),
        ),
        migrations.AddField(
            model_name='budgetversion',
            name='needs_recalculation',
            field=models.BooleanField(default=False, verbose_name='Требует пересчета'),
        ),
        migrations.AddField(
            model_name='budgetversion',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утвержден'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
