# Generated by Django 5.2.10 on 2026-04-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0004_budgetversion_approved_at_budgetversion_approved_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetversion",
            name="budget_type",
            field=models.CharField(
                choices=[
                    ("baseline", "План"),
                    ("rolling", "Текущий прогноз"),
                    ("adhoc", "Ad-hoc"),
                ],
                default="baseline",
                max_length=20,
                verbose_name="Тип бюджета",
            ),
        ),
    ]
