# Generated by Django 5.2.10 on 2026-06-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SegmentsSales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сегментный анализ",
                "verbose_name_plural": "Сегментный анализ",
                "managed": False,
            },
        ),
    ]
