# Generated by Django 5.2.10 on 2026-07-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gear", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продажи за период",
                "verbose_name_plural": "Продажи за период",
                "managed": False,
            },
        ),
    ]
