# Generated by Django 5.2.10 on 2026-07-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0002_dailysales'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostsControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Контроль закупочных цен',
                'verbose_name_plural': 'Контроль закупочных цен',
                'managed': False,
            },
        ),
    ]
