# Generated by Django 5.2.10 on 2026-07-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0003_costscontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Статистика и прочее',
                'verbose_name_plural': 'Статистика и прочее',
                'managed': False,
            },
        ),
    ]
