# Generated by Django 5.2.10 on 2026-07-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0004_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Займы и кредиты',
                'verbose_name_plural': 'Займы и кредиты',
                'managed': False,
            },
        ),
    ]
