# Generated by Django 6.0.1 on 2026-01-18 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Counterparty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(max_length=250, unique=True, verbose_name="ИНН"),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=250, verbose_name="Контрагент"
                    ),
                ),
                (
                    "logo",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Логотип (глиф)",
                    ),
                ),
                (
                    "logo_svg",
                    models.TextField(
                        blank=True, null=True, verbose_name="Логотип (SVG)"
                    ),
                ),
                (
                    "ceo",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Руководитель",
                    ),
                ),
                (
                    "ceo_post",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Должность руководителя",
                    ),
                ),
                (
                    "ceo_record_date",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Дата записи в ЕГРЮЛ (рук.)",
                    ),
                ),
                (
                    "ceo_hidden_by_fns",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="ФИО скрыто ФНС",
                    ),
                ),
                (
                    "manager_is_org",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Управляющая организация",
                    ),
                ),
                (
                    "okved_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="ОКВЭД (код)"
                    ),
                ),
                (
                    "okved_name",
                    models.CharField(
                        blank=True,
                        max_length=350,
                        null=True,
                        verbose_name="ОКВЭД (наименование)",
                    ),
                ),
                (
                    "okved_version",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="ОКВЭД (версия)",
                    ),
                ),
                (
                    "okopf_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Код ОКОПФ"
                    ),
                ),
                (
                    "okopf_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Наименование ОПФ (ОКОПФ)",
                    ),
                ),
                (
                    "risk_disq_persons",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Дисквалифицированные лица"
                    ),
                ),
                (
                    "risk_mass_directors",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Массовые руководители"
                    ),
                ),
                (
                    "risk_mass_founders",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Массовые учредители"
                    ),
                ),
                (
                    "risk_illegal_fin",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Нелегальная фин. деятельность",
                    ),
                ),
                (
                    "risk_illegal_fin_status",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Статус нелегал. фин.",
                    ),
                ),
                (
                    "risk_sanctions",
                    models.BooleanField(blank=True, null=True, verbose_name="Санкции"),
                ),
                (
                    "risk_sanctions_countries",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Страны санкций (список)",
                    ),
                ),
                (
                    "risk_sanctioned_founder",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Санкции в отношении учредителя",
                    ),
                ),
                (
                    "risk_json",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Риски (сырые данные)"
                    ),
                ),
                (
                    "was_notes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="История изменённых полей",
                    ),
                ),
                (
                    "adress",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("RU", "Россия"),
                            ("KZ", "Казахстан"),
                            ("BY", "Беларусь"),
                            ("KG", "Киргизия"),
                            ("UZ", "Узбекистан"),
                            ("TJ", "Таджикистан"),
                            ("AM", "Армения"),
                            ("AZ", "Азербайджан"),
                            ("GE", "Грузия"),
                            ("MD", "Молдова"),
                            ("UA", "Украина"),
                            ("EE", "Эстония"),
                            ("LV", "Латвия"),
                            ("LT", "Литва"),
                            ("PL", "Польша"),
                            ("DE", "Германия"),
                            ("FR", "Франция"),
                            ("IT", "Италия"),
                            ("ES", "Испания"),
                            ("PT", "Португалия"),
                            ("GR", "Греция"),
                            ("CY", "Кипр"),
                            ("TR", "Турция"),
                            ("CN", "Китай"),
                            ("JP", "Япония"),
                            ("KR", "Корея"),
                            ("US", "США"),
                            ("CA", "Канада"),
                            ("BR", "Бразилия"),
                            ("AU", "Австралия"),
                            ("NZ", "Новая Зеландия"),
                            ("GB", "Великобритания"),
                            ("IE", "Ирландия"),
                            ("NL", "Нидерланды"),
                            ("BE", "Бельгия"),
                            ("LU", "Люксембург"),
                            ("DK", "Дания"),
                            ("SE", "Швеция"),
                            ("NO", "Норвегия"),
                            ("FI", "Финляндия"),
                            ("IS", "Исландия"),
                            ("CH", "Швейцария"),
                            ("AT", "Австрия"),
                            ("HU", "Венгрия"),
                            ("CZ", "Чехия"),
                            ("SK", "Словакия"),
                            ("SI", "Словения"),
                            ("HR", "Хорватия"),
                            ("BA", "Босния и Герцеговина"),
                            ("RS", "Сербия"),
                            ("ME", "Черногория"),
                            ("MK", "Македония"),
                            ("AL", "Албания"),
                            ("BG", "Болгария"),
                            ("RO", "Румыния"),
                        ],
                        default="RU",
                        max_length=20,
                        verbose_name="Страна",
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Сайт"),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Тел."
                    ),
                ),
                (
                    "ogrn",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="ОГРН"
                    ),
                ),
                (
                    "kpp",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="КПП/ОКПО"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Регион"
                    ),
                ),
                (
                    "fullname",
                    models.CharField(
                        blank=True,
                        max_length=350,
                        null=True,
                        verbose_name="Полн. Наименование",
                    ),
                ),
                (
                    "taxregime",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Налоговый режим",
                    ),
                ),
                (
                    "checko_updated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата последнего обновления данных из ФНС / Checko",
                        null=True,
                        verbose_name="Данные ФНС обновлены",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контрагент",
                "verbose_name_plural": "Контрагенты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Gr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Группа")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Группа контрагентов",
                "verbose_name_plural": "Группы контрагентов",
            },
        ),
        migrations.CreateModel(
            name="CounterpartyFinancialYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(db_index=True, verbose_name="Год"),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Выручка",
                    ),
                ),
                (
                    "net_profit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Чистая прибыль",
                    ),
                ),
                (
                    "equity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Собственный капитал",
                    ),
                ),
                (
                    "payables",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Кредиторская задолженность",
                    ),
                ),
                (
                    "share_capital",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Уставный капитал",
                    ),
                ),
                (
                    "cf_operating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="ДДС от операц. деят-ти",
                    ),
                ),
                (
                    "liabilities_long",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Долгосрочные обязательства (1400)",
                    ),
                ),
                (
                    "liabilities_short",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Краткосрочные обязательства (1500)",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Источник данных",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financials",
                        to="counterparties.counterparty",
                        verbose_name="Контрагент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Финансовый год контрагента",
                "verbose_name_plural": "Финансовые годы контрагентов",
                "ordering": ["-year"],
            },
        ),
        migrations.AddField(
            model_name="counterparty",
            name="gr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="counterparties.gr",
                verbose_name="Группа",
            ),
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "counterparty",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant",
                        to="counterparties.counterparty",
                        verbose_name="Контрагент",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответ. лицо",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кабинет контрагента",
                "verbose_name_plural": "Кабинеты контрагентов",
                "ordering": ["counterparty"],
            },
        ),
    ]
