# Generated by Django 5.2.10 on 2026-01-19 03:25

import contracts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("corporate", "0004_remove_bankaccount_bik"),
        ("counterparties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractsTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="Тип договора"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип договора",
                "verbose_name_plural": "Типы договоров",
            },
        ),
        migrations.CreateModel(
            name="Contracts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Номер"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата договора"
                    ),
                ),
                (
                    "date_signed",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата подписания"
                    ),
                ),
                (
                    "is_signed",
                    models.BooleanField(blank=True, null=True, verbose_name="Подписан"),
                ),
                (
                    "regex",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="RegEx"
                    ),
                ),
                (
                    "cp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="counterparties.counterparty",
                        verbose_name="Контрагент",
                    ),
                ),
                (
                    "defaultcf",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corporate.сfitems",
                        verbose_name="Статья CF по дефолту",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Менеджер договора",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corporate.owners",
                        verbose_name="Компания",
                    ),
                ),
                (
                    "pid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendments",
                        to="contracts.contracts",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="contracts.contractstitle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Договор",
                "verbose_name_plural": "Договоры",
            },
        ),
        migrations.CreateModel(
            name="ContractItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.CharField(
                        blank=True,
                        max_length=550,
                        null=True,
                        verbose_name="Предмет договора",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contracts.contracts",
                        verbose_name="Контрагент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предмет договора",
                "verbose_name_plural": "Предметы договоров",
            },
        ),
        migrations.CreateModel(
            name="ContractFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="описание"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=contracts.models.document_upload_path,
                        verbose_name="Файл документа",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="contracts.contracts",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Conditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True, max_length=550, null=True, verbose_name="Условие"
                    ),
                ),
                (
                    "date_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата начлала"
                    ),
                ),
                (
                    "date_finish",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "accural_finc",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Функция начислений",
                    ),
                ),
                (
                    "params",
                    models.JSONField(blank=True, null=True, verbose_name="Параметры"),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contracts.contracts",
                        verbose_name="Контрагент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Условие договора",
                "verbose_name_plural": "Условия договоров",
            },
        ),
    ]
