# Generated by Django 5.2.10 on 2026-01-20 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
        ("corporate", "0006_bankaccount_bs_acc"),
    ]

    operations = [
        migrations.AddField(
            model_name="contracts",
            name="defaultcfcr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts_default_cr",
                to="corporate.cfitems",
                verbose_name="Статья CF по дефолту для Кт",
            ),
        ),
        migrations.AlterField(
            model_name="contracts",
            name="defaultcf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts_default_dt",
                to="corporate.cfitems",
                verbose_name="Статья CF по дефолту для Дт",
            ),
        ),
        migrations.AlterField(
            model_name="contracts",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="contracts.contractstitle",
                verbose_name="Тип документа",
            ),
        ),
    ]
