# Generated by Django 5.2.10 on 2026-01-20 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_contracts_defaultcfcr_alter_contracts_defaultcf_and_more"),
        ("corporate", "0006_bankaccount_bs_acc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contracts",
            name="defaultcf",
        ),
        migrations.RemoveField(
            model_name="contracts",
            name="defaultcfcr",
        ),
        migrations.CreateModel(
            name="CfItemAuto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "regex",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="RegEx"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contracts.contracts",
                        verbose_name="Договор",
                    ),
                ),
                (
                    "defaultcfcr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts_default_cr",
                        to="corporate.cfitems",
                        verbose_name="Статья CF по дефолту для Кт",
                    ),
                ),
                (
                    "defaultcfdt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts_default_dt",
                        to="corporate.cfitems",
                        verbose_name="Статья CF по дефолту для Дт",
                    ),
                ),
            ],
            options={
                "verbose_name": "⚙️ Автоматизация",
                "verbose_name_plural": "⚙️ Автоматизация",
            },
        ),
    ]
