# Generated by Django 5.2.10 on 2026-01-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_remove_contracts_defaultcf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contracts",
            name="regex",
            field=models.TextField(blank=True, null=True, verbose_name="RegEx"),
        ),
    ]
