# Generated by Django 5.2.10 on 2026-02-24 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contracts_regex'),
        ('macro', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
            ],
            options={
                'verbose_name': 'Метод учёта',
                'verbose_name_plural': 'Методы учёта',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ConditionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('schema', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Тип условия',
                'verbose_name_plural': 'Типы условий',
            },
        ),
        migrations.RemoveField(
            model_name='conditions',
            name='accural_finc',
        ),
        migrations.RemoveField(
            model_name='conditions',
            name='condition',
        ),
        migrations.AddField(
            model_name='conditions',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='macro.taxeslist', verbose_name='Налог (например НДС)'),
        ),
        migrations.AddField(
            model_name='conditions',
            name='vat_mode',
            field=models.CharField(choices=[('included', 'НДС включён'), ('excluded', 'НДС сверху'), ('exempt', 'Без НДС / не облагается'), ('unknown', 'Не задано')], default='unknown', max_length=20, verbose_name='Режим НДС'),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='contracts.contracts', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='contractitems',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contracts', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='conditions',
            name='accounting_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conditions', to='contracts.accountingmethod', verbose_name='Метод учёта'),
        ),
        migrations.AddField(
            model_name='conditions',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contracts.conditiontype', verbose_name='Тип условия'),
        ),
        migrations.AddIndex(
            model_name='conditions',
            index=models.Index(fields=['contract', 'type'], name='contracts_c_contrac_389d59_idx'),
        ),
        migrations.AddIndex(
            model_name='conditions',
            index=models.Index(fields=['date_start', 'date_finish'], name='contracts_c_date_st_50b765_idx'),
        ),
    ]
