# Generated by Django 5.2.10 on 2026-02-24 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_accountingmethod_conditiontype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionTypeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, verbose_name='Код поля')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('field_type', models.CharField(choices=[('string', 'Текст'), ('integer', 'Целое число'), ('number', 'Число'), ('boolean', 'Да/Нет'), ('date', 'Дата'), ('currency', 'Валюта'), ('choice', 'Список (ручной)'), ('json', 'JSON')], max_length=20, verbose_name='Тип')),
                ('required', models.BooleanField(default=False, verbose_name='Обязательное?')),
                ('default', models.CharField(blank=True, max_length=250, null=True, verbose_name='Значение по умолчанию')),
                ('min_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Мин')),
                ('max_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Макс')),
                ('choices', models.JSONField(blank=True, null=True, verbose_name='Варианты (JSON)')),
                ('help_text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Подсказка')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('condition_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='contracts.conditiontype', verbose_name='Тип условия')),
            ],
            options={
                'verbose_name': 'Поле типа условия',
                'verbose_name_plural': 'Поля типов условий',
                'ordering': ('order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('condition_type', 'code'), name='uq_conditiontype_field_code')],
            },
        ),
    ]
