# Generated by Django 5.2.10 on 2026-02-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_conditiontypefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditiontypefield',
            name='default',
        ),
        migrations.AlterField(
            model_name='conditiontypefield',
            name='field_type',
            field=models.CharField(choices=[('string', 'Текст'), ('integer', 'Целое'), ('number', 'Число'), ('boolean', 'Да/Нет'), ('date', 'Дата'), ('currency', 'Валюта'), ('choice', 'Список')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='conditiontypefield',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
    ]
