# Generated by Django 5.2.10 on 2026-02-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_remove_conditiontypefield_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingmethod',
            name='code',
            field=models.SlugField(blank=True, unique=True, verbose_name='Код'),
        ),
    ]
