# Generated by Django 5.2.10 on 2026-02-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_alter_accountingmethod_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditions',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='conditions',
            name='currency',
            field=models.CharField(blank=True, choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CHF', 'CHF'), ('JPY', 'JPY'), ('CNY', 'CNY'), ('CAD', 'CAD'), ('AUD', 'AUD'), ('HKD', 'HKD'), ('KZT', 'KZT'), ('KGS', 'KGS'), ('UZS', 'UZS'), ('AZN', 'AZN'), ('AMD', 'AMD'), ('AED', 'AED')], max_length=3, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='conditions',
            name='period',
            field=models.CharField(blank=True, choices=[('week', 'Неделя'), ('month', 'Месяц'), ('quarter', 'Квартал'), ('year', 'Год')], max_length=10, null=True, verbose_name='Период начисления'),
        ),
    ]
