# Generated by Django 5.2.10 on 2026-02-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_conditions_amount_conditions_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditions',
            name='currency',
        ),
        migrations.AddField(
            model_name='contracts',
            name='currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CHF', 'CHF'), ('JPY', 'JPY'), ('CNY', 'CNY'), ('CAD', 'CAD'), ('AUD', 'AUD'), ('HKD', 'HKD'), ('KZT', 'KZT'), ('KGS', 'KGS'), ('UZS', 'UZS'), ('AZN', 'AZN'), ('AMD', 'AMD'), ('AED', 'AED')], default='RUB', max_length=3, verbose_name='Валюта договора'),
        ),
    ]
