# Generated by Django 5.2.10 on 2026-02-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_remove_conditions_currency_contracts_currency'),
        ('macro', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditions',
            name='type',
        ),
        migrations.RemoveField(
            model_name='conditiontypefield',
            name='condition_type',
        ),
        migrations.RemoveIndex(
            model_name='conditions',
            name='contracts_c_contrac_389d59_idx',
        ),
        migrations.AddField(
            model_name='conditions',
            name='pay_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Число месяца (1–31)', null=True, verbose_name='День оплаты'),
        ),
        migrations.AddField(
            model_name='conditions',
            name='pay_offset_days',
            field=models.IntegerField(default=0, help_text='Напр. +10 дней от расчетной даты', verbose_name='Смещение, дней'),
        ),
        migrations.AddField(
            model_name='conditions',
            name='pay_offset_months',
            field=models.IntegerField(default=0, help_text='Напр. 1 = платить в следующем месяце (после отчётного)', verbose_name='Смещение, месяцев'),
        ),
        migrations.AddField(
            model_name='conditions',
            name='pay_rule',
            field=models.CharField(choices=[('month', 'За месяц'), ('quarter', 'За квартал'), ('half_year', 'За полугодие'), ('year', 'За год'), ('m2', 'За 2 месяца'), ('m3', 'За 3 месяца'), ('m4', 'За 4 месяца'), ('custom', 'Другое (см. params)')], default='month', max_length=20, verbose_name='Период оплаты'),
        ),
        migrations.AddField(
            model_name='conditions',
            name='pay_timing',
            field=models.CharField(choices=[('prepay', 'Предоплата'), ('postpay', 'Постоплата')], default='postpay', max_length=10, verbose_name='Тип оплаты'),
        ),
        migrations.AddField(
            model_name='conditions',
            name='penalty_rate_day',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Напр. 0.1 = 0.1% в день', max_digits=8, null=True, verbose_name='Неустойка, % в день'),
        ),
        migrations.AddIndex(
            model_name='conditions',
            index=models.Index(fields=['contract'], name='contracts_c_contrac_bb0cda_idx'),
        ),
        migrations.DeleteModel(
            name='ConditionType',
        ),
        migrations.DeleteModel(
            name='ConditionTypeField',
        ),
    ]
