# Generated by Django 5.2.10 on 2026-02-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_remove_conditions_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions',
            name='pay_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='День оплаты'),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='pay_offset_days',
            field=models.IntegerField(blank=True, help_text='Напр. +10 дней от расчетной даты', null=True, verbose_name='Смещение, дней'),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='pay_offset_months',
            field=models.IntegerField(default=1, help_text='Напр. 1 = платить в след. мес', verbose_name='Смещение'),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='period',
            field=models.CharField(blank=True, choices=[('week', 'Неделя'), ('month', 'Месяц'), ('quarter', 'Квартал'), ('year', 'Год')], default='month', max_length=10, null=True, verbose_name='Период начисления'),
        ),
    ]
