# Generated by Django 5.2.10 on 2026-02-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_alter_conditions_pay_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingmethod',
            name='icon',
            field=models.CharField(blank=True, help_text='Например: 🧾 или 💳 или ✅', max_length=32, null=True, verbose_name='Иконка/эмодзи'),
        ),
    ]
