# Generated by Django 5.2.10 on 2026-02-25 03:07

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_accountingmethod_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractfiles',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AddField(
            model_name='contractfiles',
            name='doc_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата документа'),
        ),
        migrations.AddField(
            model_name='contractfiles',
            name='doc_number',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Номер документа'),
        ),
        migrations.AddField(
            model_name='contractfiles',
            name='doc_type',
            field=models.CharField(choices=[('contract', 'Договор'), ('additional', 'Доп. соглашение'), ('act', 'Акт'), ('reconciliation', 'Акт сверки'), ('invoice', 'Счёт'), ('other', 'Другое')], default='other', max_length=32, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='accountingmethod',
            name='icon',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Иконка/эмодзи'),
        ),
        migrations.AlterField(
            model_name='contractfiles',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='contractfiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=contracts.models.document_upload_path, verbose_name='Файл'),
        ),
        migrations.AddIndex(
            model_name='contractfiles',
            index=models.Index(fields=['contract', 'doc_type'], name='contracts_c_contrac_5927f5_idx'),
        ),
        migrations.AddIndex(
            model_name='contractfiles',
            index=models.Index(fields=['doc_date'], name='contracts_c_doc_dat_898dcd_idx'),
        ),
    ]
