# Generated by Django 5.2.10 on 2026-03-03 08:53

import contracts.accruals.registry
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_alter_contractfiles_options_contractfiles_doc_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditions',
            name='accrual_fn',
            field=models.CharField(choices=contracts.accruals.registry.accrual_choices, default='fixed_payments', max_length=64, verbose_name='Функция начисления'),
        ),
    ]
