# Generated by Django 5.2.10 on 2026-03-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_conditions_accrual_fn'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractfiles',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Сумма'),
        ),
    ]
