# Generated by Django 5.2.10 on 2026-03-05 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0016_contractfiles_amount"),
        ("corporate", "0015_alter_subconto_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractfiles",
            options={
                "ordering": ["doc_date", "id"],
                "verbose_name": "Файл",
                "verbose_name_plural": "Файлы",
            },
        ),
        migrations.AddField(
            model_name="contracts",
            name="bs",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="corporate.coa",
                verbose_name="Счет для рассчетов",
            ),
        ),
    ]
