# Generated by Django 5.2.10 on 2026-03-11 14:18

import contracts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0017_alter_contractfiles_options_contracts_bs"),
        ("corporate", "0015_alter_subconto_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="conditions",
            name="acc_bs",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="conditions_acc_bs",
                to="corporate.coa",
                verbose_name="Счет BS",
            ),
        ),
        migrations.AddField(
            model_name="conditions",
            name="acc_pl",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="conditions_acc_pl",
                to="corporate.coa",
                verbose_name="Счет PL",
            ),
        ),
        migrations.AddField(
            model_name="conditions",
            name="param_json",
            field=models.JSONField(blank=True, null=True, verbose_name="New Params"),
        ),
        migrations.AddField(
            model_name="conditions",
            name="subconto_bs",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="conditions_subconto_bs",
                to="corporate.cfitems",
                verbose_name="Субконто BS",
            ),
        ),
        migrations.AddField(
            model_name="conditions",
            name="subconto_pl",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="conditions_subconto_pl",
                to="corporate.cfitems",
                verbose_name="Субконто PL",
            ),
        ),
        migrations.AddField(
            model_name="conditions",
            name="vat_json",
            field=models.JSONField(
                default=contracts.models.default_vat, verbose_name="НДС по дефолту"
            ),
        ),
        migrations.CreateModel(
            name="AccuralFn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Имя функции"
                    ),
                ),
                (
                    "python_path",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="Функция локальная"
                    ),
                ),
                (
                    "server_path",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="Функция на сервере"
                    ),
                ),
                ("condition_template", models.JSONField(verbose_name="Параметры")),
                (
                    "description",
                    models.TextField(
                        help_text="Описание обязательно", verbose_name="Описание"
                    ),
                ),
                (
                    "accounting_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="contracts.accountingmethod",
                        verbose_name="Метод начислений",
                    ),
                ),
            ],
            options={
                "verbose_name": "⚙️ Функции начисления",
                "verbose_name_plural": "⚙️ Функции начисления",
            },
        ),
        migrations.AddField(
            model_name="conditions",
            name="fn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="contracts.accuralfn",
                verbose_name="New Fn",
            ),
        ),
    ]
