# Generated by Django 5.2.10 on 2026-03-11 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0018_conditions_acc_bs_conditions_acc_pl_and_more"),
        ("corporate", "0015_alter_subconto_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accuralfn",
            options={
                "verbose_name": "⚙️ Функция начислений",
                "verbose_name_plural": "⚙️ Функции начислений",
            },
        ),
        migrations.AddField(
            model_name="contracts",
            name="pl",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acc_pl",
                to="corporate.coa",
                verbose_name="Счет PL",
            ),
        ),
        migrations.AddField(
            model_name="contracts",
            name="st",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acc_bs",
                to="corporate.coa",
                verbose_name="Счет BS",
            ),
        ),
        migrations.AddField(
            model_name="contracts",
            name="subconto_bs",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subconto_bs",
                to="corporate.cfitems",
                verbose_name="Субконто BS",
            ),
        ),
        migrations.AddField(
            model_name="contracts",
            name="subconto_pl",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subconto_pl",
                to="corporate.cfitems",
                verbose_name="Субконто PL",
            ),
        ),
        migrations.AlterField(
            model_name="contracts",
            name="bs",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acc_st",
                to="corporate.coa",
                verbose_name="Счет ST",
            ),
        ),
    ]
