# Generated by Django 5.2.10 on 2026-02-25 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "subject_id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, verbose_name="subject_id"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Категория"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "nm_id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, verbose_name="Артукул WB"
                    ),
                ),
                (
                    "sa_name",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Артикул продавца",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "imtID",
                    models.BigIntegerField(blank=True, null=True, verbose_name="imtID"),
                ),
                (
                    "nmUUID",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="nmUUID"
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Бренд"
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(blank=True, null=True, verbose_name="Создано"),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Обновлено"
                    ),
                ),
                (
                    "tnved",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="ТНВЭД"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Пол"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Страна производитель",
                    ),
                ),
                (
                    "vat_rate",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Указанная ставка НДС",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wb.subject",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Каталог WB",
            },
        ),
    ]
