# Generated by Django 5.2.10 on 2026-04-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechSize",
            fields=[
                (
                    "size",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Размер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тех. размер",
                "verbose_name_plural": "Тех. размеры",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="tech_sizes",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="wb.techsize",
                verbose_name="Тех. размеры",
            ),
        ),
    ]
