# Generated by Django 6.0.1 on 2026-01-18 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "bik",
                    models.CharField(max_length=9, unique=True, verbose_name="БИК"),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Адрес"),
                ),
                (
                    "corr_account",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Кор. счёт"
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        blank=True, max_length=12, null=True, verbose_name="ИНН"
                    ),
                ),
                (
                    "kpp",
                    models.CharField(
                        blank=True, max_length=9, null=True, verbose_name="КПП"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Тип"
                    ),
                ),
                (
                    "name_eng",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Наименование (англ.)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Банк",
                "verbose_name_plural": "Банки",
            },
        ),
        migrations.CreateModel(
            name="Owners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Наименование"
                    ),
                ),
                (
                    "inn",
                    models.CharField(max_length=255, unique=True, verbose_name="ИНН"),
                ),
                (
                    "kpp",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="КПП"
                    ),
                ),
                (
                    "ogrn",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="ОГРН"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Адрес"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Сайт"),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Полное наименование",
                    ),
                ),
                (
                    "ceo_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Руководитель",
                    ),
                ),
                (
                    "ceo_post",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Должность"
                    ),
                ),
                (
                    "ceo_record_date",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Дата назначения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Собственник",
                "verbose_name_plural": "Собственники",
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bik", models.CharField(max_length=9, verbose_name="БИК")),
                (
                    "account",
                    models.CharField(max_length=255, unique=True, verbose_name="Счет"),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("RUB", "RUB"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                            ("CHF", "CHF"),
                            ("JPY", "JPY"),
                            ("CNY", "CNY"),
                            ("CAD", "CAD"),
                            ("AUD", "AUD"),
                            ("HKD", "HKD"),
                            ("KZT", "KZT"),
                            ("KGS", "KGS"),
                            ("UZS", "UZS"),
                            ("AZN", "AZN"),
                            ("AMD", "AMD"),
                            ("AED", "AED"),
                        ],
                        default="RUB",
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="corporate.bank",
                        verbose_name="Банк",
                    ),
                ),
                (
                    "corporate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corporate.owners",
                        verbose_name="Собственник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Банковский счет",
                "verbose_name_plural": "Банковские счета",
            },
        ),
    ]
