# Generated by Django 6.0.1 on 2026-01-18 06:16

import django.core.validators
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="owners",
            options={
                "verbose_name": "Компании",
                "verbose_name_plural": "Группа компаний",
            },
        ),
        migrations.CreateModel(
            name="COA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="6 цифр - уникальный",
                        max_length=6,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Код должен состоять ровно из 6 цифр",
                                regex="^\\d{6}$",
                            )
                        ],
                        verbose_name="Код",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "desctiption",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="corporate.coa",
                        verbose_name="Родитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Счет",
                "verbose_name_plural": "План счетов",
            },
        ),
        migrations.CreateModel(
            name="СfItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="6 цифр - уникальный",
                        max_length=6,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Код должен состоять ровно из 6 цифр",
                                regex="^\\d{6}$",
                            )
                        ],
                        verbose_name="Код",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "desctiption",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="corporate.сfitems",
                        verbose_name="Родитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья ДС",
                "verbose_name_plural": "Статьи ДС",
            },
        ),
    ]
