# Generated by Django 6.0.1 on 2026-01-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0002_alter_owners_options_coa_сfitems"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="owners",
            options={
                "verbose_name": "Собственник",
                "verbose_name_plural": "Собственники",
            },
        ),
        migrations.AddField(
            model_name="bank",
            name="logo",
            field=models.CharField(
                blank=True,
                help_text="Символ-глиф банка",
                max_length=1,
                null=True,
                verbose_name="Логотип (глиф)",
            ),
        ),
    ]
