# Generated by Django 5.2.10 on 2026-01-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0003_alter_owners_options_bank_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='bik',
        ),
    ]
