# Generated by Django 5.2.10 on 2026-01-20 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
        ("corporate", "0004_remove_bankaccount_bik"),
        ("treasury", "0003_cfdata"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="СfItems",
            new_name="CfItems",
        ),
    ]
