# Generated by Django 5.2.10 on 2026-01-20 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0005_rename_сfitems_cfitems"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="bs_acc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="corporate.coa",
                verbose_name="Балансовый счет",
            ),
        ),
    ]
