# Generated by Django 5.2.10 on 2026-01-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0006_bankaccount_bs_acc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owners",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Наименование собственника"
            ),
        ),
    ]
