# Generated by Django 5.2.10 on 2026-01-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0007_alter_owners_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Countries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Наименование")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=3, null=True, verbose_name="Код старны"
                    ),
                ),
                (
                    "emojy_flag",
                    models.CharField(
                        blank=True, max_length=3, null=True, verbose_name="Код старны"
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        blank=True, max_length=3, null=True, verbose_name="Код старны"
                    ),
                ),
                (
                    "regex_patterns",
                    models.TextField(
                        blank=True,
                        help_text="RegEx",
                        null=True,
                        verbose_name="Поисковая модель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страна",
                "verbose_name_plural": "Страны",
            },
        ),
    ]
