# Generated by Django 5.2.10 on 2026-01-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0008_countries"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="countries",
            options={"verbose_name": "География", "verbose_name_plural": "География"},
        ),
        migrations.AlterField(
            model_name="countries",
            name="currency_code",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="Код валюты"
            ),
        ),
        migrations.AlterField(
            model_name="countries",
            name="emojy_flag",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Флаг"
            ),
        ),
    ]
