# Generated by Django 5.2.10 on 2026-02-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0009_alter_countries_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bank",
            name="bik",
            field=models.CharField(
                help_text="9 цифр, без пробелов",
                max_length=9,
                unique=True,
                verbose_name="БИК",
            ),
        ),
    ]
