# Generated by Django 5.2.10 on 2026-02-05 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0010_alter_bank_bik"),
    ]

    operations = [
        migrations.AddField(
            model_name="cfitems",
            name="mapping",
            field=models.ForeignKey(
                blank=True,
                help_text="Маппинг для распределения по плану счетов",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="corporate.coa",
                verbose_name="Mapping",
            ),
        ),
    ]
