# Generated by Django 5.2.10 on 2026-02-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0011_cfitems_mapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="is_active",
            field=models.BooleanField(blank=True, null=True, verbose_name="Активный"),
        ),
    ]
