# Generated by Django 5.2.10 on 2026-03-02 21:04

import django.core.validators
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0012_bankaccount_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subconto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="3 цифр - уникальный",
                        max_length=3,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Код должен состоять ровно из 3 цифр",
                                regex="^\\d{3}$",
                            )
                        ],
                        verbose_name="Код",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rgex",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="ReGex"
                    ),
                ),
                (
                    "desctiption",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="corporate.subconto",
                        verbose_name="Родитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Субконто",
                "verbose_name_plural": "Субконто справочник",
            },
        ),
    ]
