# Generated by Django 5.2.10 on 2026-03-03 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0014_alter_subconto_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subconto',
            name='code',
            field=models.CharField(help_text='4 цифры - уникальный', max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='Код должен состоять ровно из 3 цифр', regex='^\\d{4}$')], verbose_name='Код'),
        ),
    ]
