# Generated by Django 5.2.10 on 2026-03-17 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0015_alter_subconto_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="COAFn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Имя функции"
                    ),
                ),
                (
                    "python_path",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="Функция локальная"
                    ),
                ),
                (
                    "server_path",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="Функция на сервере"
                    ),
                ),
                (
                    "condition_template",
                    models.JSONField(default=dict, verbose_name="Параметры"),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Описание обязательно", verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Функция плана счетов",
                "verbose_name_plural": "Функции планов счетов",
            },
        ),
        migrations.CreateModel(
            name="ConditionsCOA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "param_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Параметры"
                    ),
                ),
                (
                    "acc_bs",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conditions_bs_target",
                        to="corporate.coa",
                        verbose_name="Счет BS",
                    ),
                ),
                (
                    "acc_pl",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conditions_pl_target",
                        to="corporate.coa",
                        verbose_name="Счет PL",
                    ),
                ),
                (
                    "coa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions_source_acc",
                        to="corporate.coa",
                        verbose_name="Счет",
                    ),
                ),
                (
                    "fn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="corporate.coafn",
                        verbose_name="Функция плана счетов",
                    ),
                ),
                (
                    "subconto_bs",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conditions_subconto_bs_target",
                        to="corporate.cfitems",
                        verbose_name="Субконто BS",
                    ),
                ),
                (
                    "subconto_pl",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conditions_subconto_pl_target",
                        to="corporate.cfitems",
                        verbose_name="Субконто PL",
                    ),
                ),
            ],
            options={
                "verbose_name": "Списание",
                "verbose_name_plural": "Списания",
            },
        ),
    ]
