DEFAULT_ANALYSIS_DAYS = 7

COMPARE_PREVIOUS_PERIOD = "previous_period"
COMPARE_PREVIOUS_WEEK = "previous_week"
COMPARE_PREVIOUS_MONTH = "previous_month"
COMPARE_PREVIOUS_YEAR = "previous_year"

SIGNIFICANT_CHANGE_PCT = 10.0
CRITICAL_CHANGE_PCT = 20.0
HIGH_RETURN_RATE_PCT = 15.0
VERY_HIGH_RETURN_RATE_PCT = 25.0


# Анализ ассортимента и запасов
ENTITY_TOP_N = 15
PRODUCT_TOP_N = 30

STOCK_SHORTAGE_DAYS = 7.0
STOCK_WARNING_DAYS = 14.0
STOCK_EXCESS_DAYS = 120.0
STOCK_DEAD_DAYS = 180.0

SALES_DROP_WARNING_PCT = -20.0
SALES_DROP_CRITICAL_PCT = -40.0
RETURNS_GROWTH_WARNING_PCT = 20.0

MIN_ENTITY_REVENUE = 10_000.0
MIN_PRODUCT_REVENUE = 1_000.0
