# Generated by Django 5.2.10 on 2026-03-28 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='accounting_uploads/', verbose_name='Файл Excel')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountingAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Счет')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('done', 'Готов'), ('error', 'Ошибка')], default='new', max_length=20, verbose_name='Статус')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='accounting_reports/', verbose_name='Отчет')),
                ('error_text', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто запустил')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='accounting_analysis.accountingupload', verbose_name='Файл')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_analysis.analysisscript', verbose_name='Сценарий')),
            ],
        ),
        migrations.CreateModel(
            name='AccountingMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20, verbose_name='Счет')),
                ('metric_name', models.CharField(max_length=100, verbose_name='Показатель')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Значение')),
                ('period', models.DateField(verbose_name='Дата')),
                ('period_type', models.CharField(choices=[('month_end', 'Конец месяца'), ('day', 'День')], default='month_end', max_length=20, verbose_name='Тип периода')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_analysis.accountinganalysis', verbose_name='Анализ')),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_analysis.accountingupload', verbose_name='Файл')),
            ],
            options={
                'unique_together': {('analysis', 'account', 'metric_name', 'period')},
            },
        ),
    ]
