# Generated by Django 5.2.10 on 2026-03-28 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingmetric',
            name='upload',
        ),
        migrations.RemoveField(
            model_name='accountinganalysis',
            name='upload',
        ),
        migrations.AddField(
            model_name='accountinganalysis',
            name='file',
            field=models.FileField(default=None, upload_to='accounting_uploads/', verbose_name='Файл Excel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountinganalysis',
            name='name',
            field=models.CharField(default='Без названия', max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountinganalysis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
        migrations.AlterField(
            model_name='accountingmetric',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='accounting_analysis.accountinganalysis', verbose_name='Анализ'),
        ),
        migrations.DeleteModel(
            name='AccountingUpload',
        ),
    ]
