# Generated by Django 5.2.10 on 2026-03-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_analysis", "0002_remove_accountingmetric_upload_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountinganalysis",
            options={
                "verbose_name": "Анализ файла",
                "verbose_name_plural": "Анализы файлов",
            },
        ),
        migrations.AlterModelOptions(
            name="accountingmetric",
            options={"verbose_name": "Показатель", "verbose_name_plural": "Показатели"},
        ),
        migrations.AlterModelOptions(
            name="analysisscript",
            options={"verbose_name": "Функции", "verbose_name_plural": "Функции"},
        ),
        migrations.AlterField(
            model_name="accountinganalysis",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="accountingmetric",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
    ]
