"""
Django settings for ts project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
# Загружаем .env
load_dotenv()

# TELEGRAM_TOKEN = ""
# TELEGRAM_ADMIN_CHAT_ID = 
# 1326519741

# ---------------------------
# External API settings
# ---------------------------
CBR_DAILY_URL = "https://www.cbr.ru/scripts/XML_daily.asp"
CHECKO_API_KEY = 'SIwfo6CFilGM4fUX'
CHECKO_API_BANK_URL = "https://api.checko.ru/v2/bank"
CHECKO_API_COMPANY_URL = "https://api.checko.ru/v2/company"


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'fallback_secret_key')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'
ALLOWED_HOSTS = ['127.0.0.1','localhost','62.109.2.166']






# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "macro",
    "corporate",
    "counterparties",
    "mptt",    
    "django_plotly_dash.apps.DjangoPlotlyDashConfig",
    "django.contrib.humanize",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

# CRONJOBS = [
#     # каждый будний день в 7:05 утра
#     ('5 7 * * 1-5', 'macro.cron.sync_rf_ru_cron'),
# ]

# FRED_API_KEY = "ce32c0ae4b2fd116a86a7a0b0c45735b"
# FRED_API_URL = "https://api.stlouisfed.org/fred/series/observations"


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django_plotly_dash.middleware.BaseMiddleware",
    "django_plotly_dash.middleware.ExternalRedirectionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
# INSTALLED_APPS += ['dpd_static_support']
# MIDDLEWARE += ['whitenoise.middleware.WhiteNoiseMiddleware']

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django_plotly_dash.middleware.BaseMiddleware",
    "django_plotly_dash.middleware.ExternalRedirectionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

ROOT_URLCONF = "ts.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ts.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('DB_NAME', 'ts_db'),
        'USER': os.getenv('DB_USER', 'ts_user'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'strong_password'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

DATA_UPLOAD_MAX_NUMBER_FIELDS = 50000
X_FRAME_OPTIONS = 'SAMEORIGIN'

from django.conf.locale.ru import formats as ru_formats
from django.conf import settings


LANGUAGE_CODE = "ru"
LANGUAGES = [
    ("en", "English"),
    ("ru", "Русский"),
]

ru_formats.DECIMAL_SEPARATOR = "."
ru_formats.THOUSAND_SEPARATOR = ","
USE_THOUSAND_SEPARATOR = True
TIME_ZONE = "Europe/Moscow"

USE_I18N = True
USE_L10N = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"       # collectstatic будет здесь
STATICFILES_DIRS = [
    BASE_DIR / "static",                     # твоя статика для разработки
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

JAZZMIN_SETTINGS = {

    "site_title": "ТРЕНДСЕТТЕР",
    "site_header": "ТРЕНДСЕТТЕР header",
    # "site_logo": "/img/logo_short.png",
    "site_brand": "Админпанель",
    # "site_favicon": "/img/logo_short.png",
    "welcome_sign": "Добро пожаловать в панель управления",
    "show_ui_builder": True,
    "navigation_expanded": False,
    "search_model": "auth.User",
    "custom_css": "css/custom.css",



    #"hide_apps": ['scr'],
    # "hide_models": ['rr.cart'],
    "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},

        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},

        # # App with dropdown menu to all its models pages (Permissions checked against models)
        # #{"app": "rr"},
        #  {"model": "rr.cart"},

        # external url that opens in a new window (Permissions can be added)
        {"name": "Помощь", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        #{"name": "Migrations", "url": "/upload-form", "new_window": True},

    ],

    #"custom_js": None,
    "show_collapse": True,


    "related_modal_active": True,


    "icons": {
    #     # --- НЕДВИЖИМОСТЬ ---
    #     "properties": "fa-solid fa-city",

    #     "properties.ProperyGroup": "fa-solid fa-city",
    #     "properties.Property": "fa-solid fa-building",
    #     "properties.PropertyDocs": "fa-solid fa-file-alt",
    #     "properties.PropetyImages": "fa-solid fa-image",
    #     "properties.PropertyValuation": "fa-solid fa-search-dollar",
    #     "properties.PropertyKadastrValue": "fa-solid fa-balance-scale",
    #     "properties.Floor": "fa-solid fa-stairs",
    #     "properties.FloorPlan": "fa-solid fa-project-diagram",
    #     "properties.FloorSections": "fa-solid fa-th-large",
    #     "properties.PremisesType": "fa-solid fa-tags",
    #     "properties.PremissStatus": "fa-solid fa-circle-check",
    #     "properties.PremissGroups": "fa-solid fa-layer-group",
    #     "properties.Premises": "fa-solid fa-door-open",
    #     "properties.PremisesDocs": "fa-solid fa-file-alt",
    #     "properties.PremisesImages": "fa-solid fa-image",
    #     "properties.Room": "fa-solid fa-vector-square",
    #     "properties.PremisesBasket": "fa-solid fa-basket-shopping",

    #     # --- КОНТРАГЕНТЫ ---
        "counterparties": "fa-solid fa-address-book",
        "counterparties.Counterparty": "fa-solid fa-handshake",
        "counterparties.Tenant": "fa-solid fa-user-tie",
        "counterparties.Gr": "fa-solid fa-people-group",
        "counterparties.Glyph": "fa-solid fa-icons",

    #     # --- СОБСТВЕННИКИ ---
        "corporate": "fa-solid fa-building-user",
        "corporate.Owners": "fa-solid fa-building-circle-check",

        # --- БАНКИ ---
        "corporate.Bank": "fa-solid fa-landmark",
        "corporate.BankAccount": "fa-solid fa-credit-card",
        
        "corporate.COA": "fa-solid fa-sitemap",
        "corporate.СfItems": "fa-solid fa-money-bill-transfer",

    #     # --- МАКРОЭКОНОМИКА ---
        "macro": "fa-solid fa-chart-line",
        "macro.WACC": "fa-solid fa-percent",
        "macro.Inflation": "fa-solid fa-arrow-trend-up",
        "macro.CalendarExceptions": "fa-solid fa-calendar-days",
        "macro.KeyRate": "fa-solid fa-money-bill-trend-up",
        "macro.TaxesList": "fa-solid fa-file-invoice-dollar",
        "macro.CurrencyRate": "fa-solid fa-coins",
        "macro.MarketSnapshot": "fa-solid fa-magnifying-glass-chart",

    #     # --- Договоры аренжды ---
    #     "la": "fa-solid fa-file-signature ",
    #     "la.La": "fa-solid fa-file-signature",
    #     "la.Subject": "fa-solid fa-cubes",
    #     "la.LaSubjectConditions": "fa-solid fa-link",
    #     "la.LeaseTermsTypes": "fa-solid fa-percent",
    #     "la.Conditions": "fa-solid fa-sliders-h",
    #     "la.ConditionsTerms": "fa-solid fa-equals",
    #     "la.Indexation": "fa-solid fa-arrow-trend-up",
    #     "la.ProjectsType": "fa-solid fa-diagram-project",
    #     "la.LaTypes": "fa-solid fa-list-ul",
    #     "la.AmendmentsType": "fa-solid fa-file-pen",
    #     "la.LaFiles": "fa-solid fa-file-upload",
    #     "la.LaEventLog": "fa-solid fa-clipboard-list",
    #     "la.LaManage": "fa-solid fa-sitemap",


    #     # --- Телеграмм-бот ---
    #     "botconfig": "fa-brands fa-telegram",
    #     "botconfig.BotDataSource": "fa-solid fa-database",
    #     "botconfig.BotCommand": "fa-solid fa-terminal",
    #     "botconfig.BotEvent": "fa-solid fa-list-check",
    #     "botconfig.BotControl": "fa-solid fa-robot",

    #     "botconfig.BotUser": "fa-solid fa-circle-user",




    #     # --- Пользователи ---
        "auth": "fa-solid fa-users",
        "auth.Group": "fa-solid fa-users-gear",
        "auth.User": "fa-solid fa-user",

    #     # --- Служебные ---
    #     "services": "fa-solid fa-gear",
    #     "services.Migrations": "fa-solid fa-code-branch",

    #     # --- Общие ---
        "admin": "fa-solid fa-gauge",
    },
    "default_icon_parents": "fa-solid fa-folder-tree",
    "default_icon_children": "fa-solid fa-file-lines",



    # "order_with_respect_to": ["rr.Properties", "rr.Premisses", "rr.PremissesTypes", "rr.Floors", "rr.PremissesStatus", "rr.PremissesUsage", "rr.SupportDocuments"],

    "order_with_respect_to": [
        "macro",           # Макропоказатели
        "properties",      # Объекты недвижимости
        "la",              # Договоры аренды
        "counterparties",  # Контрагенты
        "corporate",       # Собственники/банки
        "botconfig",
        "auth",            # Пользователи и группы
        "services",        # Служебные — всегда в конце
    ],

    "changeform_format_overrides": {"auth.user": "vertical_tabs",},

}



JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": True,
    "footer_small_text": True,

    # текст в контенте лучше обычный размер,
    # так легче читать списки и таблицы
    "body_small_text": False,

    # логотип можно оставить мелким
    "brand_small_text": True,

    "brand_colour": "navbar-secondary",
    "accent": "accent-info",
    "navbar": "navbar-secondary navbar-dark",
    "no_navbar_border": False,

    # удобно, когда верхнее меню фиксировано
    "navbar_fixed": True,

    "layout_boxed": False,
    "footer_fixed": False,

    # фиксируем сайдбар, чтобы меню не уезжало
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",

    # меню слева чуть крупнее
    "sidebar_nav_small_text": False,

    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,

    # я бы отключил legacy-стиль и включил flat-стиль
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,

    "theme": "yeti",
    "dark_mode_theme": None,

    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    "actions_sticky_top": False,
}

# PLOTLY_DASH = {
#     "serve_locally": False,
# }

# PLOTLY_DASH = {
#     "ws_route": "ws/channel",  # нужно для WebSocket соединений (если используете live updates)
# }

# # Полностью пустой список компонентов
# PLOTLY_COMPONENTS = []

# # Также попробуйте явно отключить
# import os
# os.environ['DASH_SERVE_LOCALLY'] = 'False'


# # LOGIN_REDIRECT_URL = '/cabinet/'
# # LOGOUT_REDIRECT_URL = '/login/'


# TEMPLATES[0]['DIRS'] = [BASE_DIR / "templates"]
# LOGIN_URL = "/"                 # у тебя лендинг = экран входа
# LOGOUT_REDIRECT_URL = "/"
# REMEMBER_ME_AGE = 60 * 60 * 24 * 30

# # Чтобы "Забыли пароль?"
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# EMAIL_BCC = ["manunotify@yandex.ru"]

# EMAIL_HOST = "smtp.yandex.ru"
# EMAIL_PORT = 465
# EMAIL_USE_SSL = True

# EMAIL_HOST_USER = "manunotify@yandex.ru"
# EMAIL_HOST_PASSWORD = "ntnmbmvvmqcchowo"

# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER



# TENANT_PORTAL_SUPPORT_EMAIL = "help@yourcompany.ru"
# TENANT_PORTAL_SUPPORT_TELEGRAM = "Daria_Voiten"


# TENANT_PORTAL_OBJECT_NAME = "БЦ «Поклонка»"
# TENANT_PORTAL_OBJECT_ADDRESS = "Москва, ул. Поклонная, 3"
# TENANT_PORTAL_OBJECT_IMAGE = "/static/img/banner_winter.jpg"   # зимний баннер

# TENANT_PORTAL_OBJECT_MAP_URL = None  # можно будет дать ссылку на карту позже
# TENANT_PORTAL_OBJECT_SITE_URL = 'https://poklonkaplace.ru'         # URL сайта объекта (если есть)
# TENANT_PORTAL_OBJECT_TELEGRAM = '@poklonkaplace'


# LOGGING = {
#     "version": 1,
#     "handlers": {"console": {"class": "logging.StreamHandler"}},
#     "loggers": {
#         "django.template": {"handlers": ["console"], "level": "INFO"},
#     },
# }

# from django.core.mail import EmailMultiAlternatives, EmailMessage

# # Перехватываем отправку писем и автоматически добавляем BCC
# _original_send = EmailMessage.send

# def _send_with_bcc(self, *args, **kwargs):
#     bcc_list = getattr(settings, "EMAIL_BCC", [])
#     if bcc_list:
#         if self.bcc:
#             self.bcc += bcc_list
#         else:
#             self.bcc = bcc_list
#     return _original_send(self, *args, **kwargs)

# EmailMessage.send = _send_with_bcc
# EmailMultiAlternatives.send = _send_with_bcc


# # Увеличиваем максимальный размер тела запроса (например, до 20 МБ)
# DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20 MB
# DATA_UPLOAD_MAX_NUMBER_FIELDS = None



# REDIS_CLIENT = redis.Redis(
#     host=os.getenv('REDIS_HOST'),
#     port=os.getenv('REDIS_PORT'),
#     db=os.getenv('REDIS_DB'),
#     password=os.getenv('REDIS_PASSWORD'),
#     decode_responses=False,  # Оставляем False для работы с pickle
#     socket_connect_timeout=30,      # Таймаут подключения
#     socket_timeout=30,              # Таймаут операций
#     retry_on_timeout=True,          # Повтор при таймауте
#     max_connections=50,             # Больше соединений
#     health_check_interval=30,       # Проверка здоровья