# Generated by Django 5.2.10 on 2026-05-26 13:06

import django.db.models.deletion
import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Subtitle"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "author",
                    models.CharField(
                        default="Дарья Войтенко", max_length=255, verbose_name="Author"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        default="Трендсеттер", max_length=255, verbose_name="Company"
                    ),
                ),
                (
                    "css",
                    models.CharField(
                        default="print.css", max_length=255, verbose_name="CSS file"
                    ),
                ),
                (
                    "slide_style",
                    models.JSONField(
                        default=reports.models.get_default_slide_style,
                        verbose_name="Slide style",
                    ),
                ),
                (
                    "date_from",
                    models.DateField(blank=True, null=True, verbose_name="Date from"),
                ),
                (
                    "date_to",
                    models.DateField(blank=True, null=True, verbose_name="Date to"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("AH", "Ad-hoc"),
                            ("COB", "Close of business"),
                            ("DE", "Daily"),
                            ("WE", "Weekly"),
                            ("ME", "Monthly"),
                            ("QE", "Quarterly"),
                            ("HY", "Half-year"),
                            ("YE", "Yearly"),
                        ],
                        default="AH",
                        max_length=10,
                        verbose_name="Report type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, unique=True, verbose_name="Title"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="SlideRegistered",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "python_path",
                    models.CharField(
                        help_text="Example: reports.slides.revenue.render",
                        max_length=500,
                        unique=True,
                        verbose_name="Python path",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Slide",
                "verbose_name_plural": "Slides",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ReportConstructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=100)),
                ("filters", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="reports.report",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_slides",
                        to="reports.section",
                    ),
                ),
                (
                    "slide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_usage",
                        to="reports.slideregistered",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report constructor",
                "verbose_name_plural": "Report constructor",
                "ordering": ["order", "id"],
            },
        ),
    ]
