# Generated by Django 5.2.10 on 2026-05-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportconstructor",
            name="filters",
            field=models.JSONField(
                blank=True, default=None, null=True, verbose_name="Filters"
            ),
        ),
    ]
