# Generated by Django 6.0.1 on 2026-01-18 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalendarExceptions",
            fields=[
                (
                    "date",
                    models.DateField(
                        primary_key=True, serialize=False, verbose_name="Дата"
                    ),
                ),
                (
                    "is_working_day",
                    models.BooleanField(default=False, verbose_name="Рабочий день?"),
                ),
            ],
            options={
                "verbose_name": "Клендарь",
                "verbose_name_plural": "Календарь",
            },
        ),
        migrations.CreateModel(
            name="Inflation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата начала действия")),
                ("inflation_rate", models.FloatField(verbose_name="ИПЦ (%)")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
            ],
            options={
                "verbose_name": "ИПЦ",
                "verbose_name_plural": "ИПЦ",
            },
        ),
        migrations.CreateModel(
            name="KeyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата начала действия")),
                ("key_rate", models.FloatField(verbose_name="Ключевая ставка (%)")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
            ],
            options={
                "verbose_name": "Ключевая ставка",
                "verbose_name_plural": "Ключевые ставки",
            },
        ),
        migrations.CreateModel(
            name="TaxesList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tax_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Наименование налога"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Налог",
                "verbose_name_plural": "Налоги",
            },
        ),
        migrations.CreateModel(
            name="WACC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата начала действия")),
                ("wacc", models.FloatField(verbose_name="WACC (%)")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
            ],
            options={
                "verbose_name": "WACC",
                "verbose_name_plural": "WACC",
            },
        ),
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата курса")),
                (
                    "base_currency",
                    models.CharField(
                        choices=[
                            ("RUB", "RUB"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                            ("CHF", "CHF"),
                            ("JPY", "JPY"),
                            ("CNY", "CNY"),
                            ("CAD", "CAD"),
                            ("AUD", "AUD"),
                            ("HKD", "HKD"),
                            ("KZT", "KZT"),
                            ("KGS", "KGS"),
                            ("UZS", "UZS"),
                            ("AZN", "AZN"),
                            ("AMD", "AMD"),
                            ("AED", "AED"),
                        ],
                        default="RUB",
                        max_length=3,
                        verbose_name="Базовая валюта",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("RUB", "RUB"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                            ("CHF", "CHF"),
                            ("JPY", "JPY"),
                            ("CNY", "CNY"),
                            ("CAD", "CAD"),
                            ("AUD", "AUD"),
                            ("HKD", "HKD"),
                            ("KZT", "KZT"),
                            ("KGS", "KGS"),
                            ("UZS", "UZS"),
                            ("AZN", "AZN"),
                            ("AMD", "AMD"),
                            ("AED", "AED"),
                        ],
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Сколько базовой валюты за 1 единицу выбранной валюты",
                        max_digits=12,
                        verbose_name="Курс",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Например: ЦБ РФ, ECB и т.п.",
                        max_length=255,
                        null=True,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
            ],
            options={
                "verbose_name": "Курс валюты",
                "verbose_name_plural": "Курсы валют",
                "ordering": ["-date", "currency"],
                "unique_together": {("date", "base_currency", "currency")},
            },
        ),
        migrations.CreateModel(
            name="TaxRates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата начала действия")),
                ("rate", models.FloatField(verbose_name="Ставка (%)")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="macro.taxeslist",
                        verbose_name="Налог",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ставки налогов",
                "verbose_name_plural": "Ставки налогов",
            },
        ),
    ]
