# Generated by Django 6.0.1 on 2026-01-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("macro", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CurrencyRate",
        ),
    ]
