# Generated by Django 6.0.1 on 2026-01-18 09:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("macro", "0002_delete_currencyrate"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketDistrict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Район / округ"),
                ),
            ],
            options={
                "verbose_name": "Рынок: район",
                "verbose_name_plural": "Рынок: районы",
            },
        ),
        migrations.CreateModel(
            name="MarketRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Город / регион"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рынок: регион",
                "verbose_name_plural": "Рынок: регионы",
            },
        ),
        migrations.CreateModel(
            name="MarketSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Код источника"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Рынок: источник",
                "verbose_name_plural": "Рынок: источники",
            },
        ),
        migrations.CreateModel(
            name="OfficeClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="A, B, C, UNKNOWN",
                        max_length=20,
                        unique=True,
                        verbose_name="Код",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Рынок: класс объекта",
                "verbose_name_plural": "Рынок: классы объектов",
            },
        ),
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="office, parking, warehouse, retail и т.п.",
                        max_length=50,
                        unique=True,
                        verbose_name="Код",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен?"),
                ),
            ],
            options={
                "verbose_name": "Рынок: тип недвижимости",
                "verbose_name_plural": "Рынок: типы недвижимости",
            },
        ),
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата курса")),
                (
                    "base_currency",
                    models.CharField(
                        choices=[
                            ("RUB", "RUB"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                            ("CHF", "CHF"),
                            ("JPY", "JPY"),
                            ("CNY", "CNY"),
                            ("CAD", "CAD"),
                            ("AUD", "AUD"),
                            ("HKD", "HKD"),
                            ("KZT", "KZT"),
                            ("KGS", "KGS"),
                            ("UZS", "UZS"),
                            ("AZN", "AZN"),
                            ("AMD", "AMD"),
                            ("AED", "AED"),
                        ],
                        default="RUB",
                        max_length=3,
                        verbose_name="Базовая валюта",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("RUB", "RUB"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                            ("CHF", "CHF"),
                            ("JPY", "JPY"),
                            ("CNY", "CNY"),
                            ("CAD", "CAD"),
                            ("AUD", "AUD"),
                            ("HKD", "HKD"),
                            ("KZT", "KZT"),
                            ("KGS", "KGS"),
                            ("UZS", "UZS"),
                            ("AZN", "AZN"),
                            ("AMD", "AMD"),
                            ("AED", "AED"),
                        ],
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Сколько базовой валюты за 1 единицу выбранной валюты",
                        max_digits=12,
                        verbose_name="Курс",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Например: ЦБ РФ, ECB и т.п.",
                        max_length=255,
                        null=True,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
            ],
            options={
                "verbose_name": "Курс валюты",
                "verbose_name_plural": "Курсы валют",
                "ordering": ["-date", "currency"],
                "unique_together": {("date", "base_currency", "currency")},
            },
        ),
        migrations.CreateModel(
            name="MarketListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(max_length=128, verbose_name="ID в источнике"),
                ),
                ("url", models.URLField(verbose_name="Ссылка")),
                (
                    "deal_type",
                    models.CharField(
                        choices=[("rent", "Аренда"), ("sale", "Продажа")],
                        max_length=20,
                        verbose_name="Тип сделки",
                    ),
                ),
                (
                    "office_class_raw",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Класс (сырой)",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "address_text",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Адрес (текст)",
                    ),
                ),
                (
                    "lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Широта",
                    ),
                ),
                (
                    "lon",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="macro.marketdistrict",
                        verbose_name="Район",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="macro.marketregion",
                        verbose_name="Город / регион",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="macro.marketsource",
                        verbose_name="Источник",
                    ),
                ),
                (
                    "office_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="macro.officeclass",
                        verbose_name="Класс",
                    ),
                ),
                (
                    "property_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="macro.propertytype",
                        verbose_name="Тип недвижимости",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рынок: объявление",
                "verbose_name_plural": "Рынок: объявления",
            },
        ),
        migrations.AddField(
            model_name="marketdistrict",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districts",
                to="macro.marketregion",
                verbose_name="Город / регион",
            ),
        ),
        migrations.CreateModel(
            name="MarketListingObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observed_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Дата наблюдения",
                    ),
                ),
                (
                    "observed_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Дата наблюдения (день)",
                    ),
                ),
                (
                    "raw",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Сырые данные (JSON/слепок)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активно"
                    ),
                ),
                (
                    "area_m2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Площадь, м²",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("RUB", "RUB"), ("USD", "USD"), ("EUR", "EUR")],
                        default="RUB",
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "price_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Цена всего",
                    ),
                ),
                (
                    "rent_rate_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Ставка",
                    ),
                ),
                (
                    "rent_rate_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("m2_month", "₽/м²/мес"),
                            ("m2_year", "₽/м²/год"),
                            ("total_month", "₽/мес"),
                            ("total_year", "₽/год"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Ед. ставки",
                    ),
                ),
                (
                    "vat_included",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="НДС включён"
                    ),
                ),
                (
                    "opex_included",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="OPEX включён"
                    ),
                ),
                (
                    "norm_rub_m2_month",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Норм. ставка, ₽/м²/мес",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="macro.marketlisting",
                        verbose_name="Объявление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рынок: наблюдение",
                "verbose_name_plural": "Рынок: наблюдения",
                "indexes": [
                    models.Index(
                        fields=["listing", "observed_date"],
                        name="macro_marke_listing_2b7754_idx",
                    ),
                    models.Index(
                        fields=["listing", "-observed_at"],
                        name="macro_marke_listing_c48a94_idx",
                    ),
                    models.Index(
                        fields=["observed_at"], name="macro_marke_observe_95e2f4_idx"
                    ),
                    models.Index(
                        fields=["is_active", "observed_at"],
                        name="macro_marke_is_acti_5bec63_idx",
                    ),
                    models.Index(
                        fields=["norm_rub_m2_month"],
                        name="macro_marke_norm_ru_c999f5_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("listing", "observed_date"), name="uq_obs_listing_day"
                    )
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name="marketdistrict",
            unique_together={("region", "name")},
        ),
        migrations.CreateModel(
            name="MarketSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateField(verbose_name="Период")),
                (
                    "deal_type",
                    models.CharField(
                        choices=[("rent", "Аренда"), ("sale", "Продажа")],
                        max_length=20,
                        verbose_name="Тип сделки",
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        default="norm_rub_m2_month",
                        max_length=30,
                        verbose_name="Метрика",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=3, verbose_name="Валюта"
                    ),
                ),
                (
                    "listings_count",
                    models.IntegerField(verbose_name="Кол-во объявлений"),
                ),
                (
                    "median_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="Медиана"
                    ),
                ),
                (
                    "p25_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="P25",
                    ),
                ),
                (
                    "p75_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="P75",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="macro.marketdistrict",
                        verbose_name="Район",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="macro.marketregion",
                        verbose_name="Город / регион",
                    ),
                ),
                (
                    "office_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="macro.officeclass",
                        verbose_name="Класс",
                    ),
                ),
                (
                    "property_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="macro.propertytype",
                        verbose_name="Тип недвижимости",
                    ),
                ),
            ],
            options={
                "verbose_name": "Анализ рынка",
                "verbose_name_plural": "Анализ рынка",
                "indexes": [
                    models.Index(
                        fields=[
                            "period",
                            "property_type",
                            "region",
                            "district",
                            "office_class",
                            "deal_type",
                        ],
                        name="macro_marke_period_fb75e6_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "period",
                            "property_type",
                            "deal_type",
                            "region",
                            "district",
                            "office_class",
                            "metric",
                        ),
                        name="uq_market_snapshot_segment_metric",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="marketlisting",
            index=models.Index(
                fields=[
                    "property_type",
                    "region",
                    "district",
                    "office_class",
                    "deal_type",
                ],
                name="macro_marke_propert_c03064_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketlisting",
            index=models.Index(
                fields=["updated_at"], name="macro_marke_updated_2bbf8d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketlisting",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id"),
                name="uq_market_listing_source_external_id",
            ),
        ),
    ]
