# Generated by Django 5.2.10 on 2026-03-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macro', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrates',
            name='income_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Предел дохода'),
        ),
    ]
