# Generated by Django 5.2.10 on 2026-01-19 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("corporate", "0004_remove_bankaccount_bik"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankStatements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="migrations/", verbose_name="Файл миграции"
                    ),
                ),
                ("start", models.DateField(blank=True, null=True, verbose_name="C")),
                ("finish", models.DateField(blank=True, null=True, verbose_name="По")),
                (
                    "bb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Начальный остаток",
                    ),
                ),
                (
                    "eb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Конечный остаток",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "ba",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corporate.bankaccount",
                        verbose_name="Счет",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corporate.owners",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выписка",
                "verbose_name_plural": "Выписки",
            },
        ),
    ]
