# Generated by Django 5.2.10 on 2026-01-19 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0004_remove_bankaccount_bik"),
        ("treasury", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankstatements",
            name="ba",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="corporate.bankaccount",
                verbose_name="Счет",
            ),
        ),
        migrations.AlterField(
            model_name="bankstatements",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="corporate.owners",
                verbose_name="Компания",
            ),
        ),
    ]
