# Generated by Django 5.2.10 on 2026-01-20 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
        ("corporate", "0004_remove_bankaccount_bik"),
        ("counterparties", "0001_initial"),
        ("treasury", "0002_alter_bankstatements_ba_alter_bankstatements_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="CfData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Документ"
                    ),
                ),
                (
                    "doc_numner",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Номер"
                    ),
                ),
                (
                    "doc_date",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Дата"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата платежа"
                    ),
                ),
                (
                    "dt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Дт",
                    ),
                ),
                (
                    "cr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Кр",
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="ИНН"
                    ),
                ),
                (
                    "temp",
                    models.TextField(blank=True, null=True, verbose_name="Назначение"),
                ),
                (
                    "cp_bs_name",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Имя в выписке",
                    ),
                ),
                ("intercompany", models.BooleanField(verbose_name="Внутрегрупповой")),
                (
                    "payer_account",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Счет плательщика",
                    ),
                ),
                (
                    "reciver_account",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Счет получателя",
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="НДС",
                    ),
                ),
                (
                    "bs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="treasury.bankstatements",
                        verbose_name="Выписка",
                    ),
                ),
                (
                    "cfitem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corporate.cfitems",
                        verbose_name="Статья CF",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contracts.contracts",
                        verbose_name="Договор",
                    ),
                ),
                (
                    "cp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cp_init",
                        to="counterparties.counterparty",
                        verbose_name="Контрагент",
                    ),
                ),
                (
                    "cp_final",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cp_final",
                        to="counterparties.counterparty",
                        verbose_name="Контрагент финальный",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corporate.owners",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "CF документ",
                "verbose_name_plural": "CF документы",
            },
        ),
    ]
