# Generated by Django 5.2.10 on 2026-01-20 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treasury", "0003_cfdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cfdata",
            name="bs",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="treasury.bankstatements",
                verbose_name="Выписка",
            ),
        ),
    ]
