# Generated by Django 5.2.10 on 2026-01-20 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0006_bankaccount_bs_acc"),
        ("treasury", "0004_alter_cfdata_bs"),
    ]

    operations = [
        migrations.AddField(
            model_name="cfdata",
            name="ba",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="corporate.bankaccount",
                verbose_name="Расчетный счет",
            ),
        ),
    ]
