# Generated by Django 5.2.10 on 2026-01-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
        ("corporate", "0006_bankaccount_bs_acc"),
        ("counterparties", "0001_initial"),
        ("treasury", "0005_cfdata_ba"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cfdata",
            constraint=models.UniqueConstraint(
                fields=("bs", "doc_numner", "date", "dt", "cr"),
                name="uniq_cfdata_bs_row",
            ),
        ),
    ]
