# Generated by Django 5.2.10 on 2026-01-20 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_contracts_defaultcfcr_alter_contracts_defaultcf_and_more"),
        ("corporate", "0006_bankaccount_bs_acc"),
        ("treasury", "0006_cfdata_uniq_cfdata_bs_row"),
    ]

    operations = [
        migrations.CreateModel(
            name="CfSplits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Дт",
                    ),
                ),
                (
                    "cr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Кр",
                    ),
                ),
                (
                    "temp",
                    models.TextField(blank=True, null=True, verbose_name="Назначение"),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="НДС",
                    ),
                ),
                (
                    "cfitem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corporate.cfitems",
                        verbose_name="Статья CF",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contracts.contracts",
                        verbose_name="Договор",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="treasury.cfdata",
                        verbose_name="Транскация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сплит",
                "verbose_name_plural": "Сплиты оплат",
            },
        ),
    ]
