# Generated by Django 5.2.10 on 2026-01-20 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counterparties", "0001_initial"),
        ("treasury", "0007_cfsplits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cfdata",
            name="cp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cp_init",
                to="counterparties.counterparty",
                verbose_name="Контрагент по ИНН в выписке",
            ),
        ),
    ]
