# Generated by Django 5.2.10 on 2026-01-23 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_remove_contracts_defaultcf_and_more"),
        ("counterparties", "0001_initial"),
        ("treasury", "0008_alter_cfdata_cp"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractsRexex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "regex",
                    models.CharField(
                        default="^.*$", max_length=500, verbose_name="RegEx"
                    ),
                ),
                ("comments", models.TextField(verbose_name="Комментарии")),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contracts.contracts",
                        verbose_name="Договор",
                    ),
                ),
                (
                    "cp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="counterparties.counterparty",
                        verbose_name="Контрагент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Автоматизация",
                "verbose_name_plural": "Автоматизация",
            },
        ),
    ]
