# Generated by Django 5.2.10 on 2026-02-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("treasury", "0009_contractsrexex"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cfsplits",
            options={
                "verbose_name": "🧩<b>Сплит оплат</b>",
                "verbose_name_plural": "🧩<b>Сплит оплат</b>",
            },
        ),
    ]
