# Generated by Django 5.2.10 on 2026-03-11 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0010_alter_cfsplits_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfdata',
            name='source_cr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Исходный Кр'),
        ),
        migrations.AddField(
            model_name='cfdata',
            name='source_dt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Исходный Дт'),
        ),
        migrations.AlterField(
            model_name='cfsplits',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='treasury.cfdata', verbose_name='Транскация'),
        ),
    ]
