# Generated by Django 5.2.10 on 2026-05-01 12:50

import django.core.validators
import django.db.models.deletion
import inventories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата поставки")),
                (
                    "number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Номер поставки"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="deliveries/csv/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["csv"]
                            )
                        ],
                        verbose_name="CSV-упаковочный файл",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Короткое описание", verbose_name="Описание поставки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставка",
                "verbose_name_plural": "Поставки",
            },
        ),
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название лота"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание лота")),
            ],
            options={
                "verbose_name": "Лот",
                "verbose_name_plural": "Лоты",
            },
        ),
        migrations.CreateModel(
            name="DeliveryFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=inventories.models.delivery_file_upload_to,
                        verbose_name="Файл",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название файла"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="inventories.delivery",
                        verbose_name="Поставка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл поставки",
                "verbose_name_plural": "Файлы поставки",
            },
        ),
        migrations.AddField(
            model_name="delivery",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventories.lot",
                verbose_name="Лот",
            ),
        ),
        migrations.CreateModel(
            name="LotFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=inventories.models.lot_file_upload_to,
                        verbose_name="Файл",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название файла"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="inventories.lot",
                        verbose_name="Лот",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл лота",
                "verbose_name_plural": "Файлы лота",
            },
        ),
    ]
