# Generated by Django 5.2.10 on 2026-05-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WbCardRaw",
            fields=[
                ("nm_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("payload", models.JSONField()),
                ("loaded_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "wb_cards_raw",
            },
        ),
    ]
