# Generated by Django 5.2.10 on 2026-05-08 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WbSizes",
            fields=[
                ("chrt_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("tech_size", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "nm",
                    models.ForeignKey(
                        db_column="nm_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sizes",
                        to="cards.wbcardraw",
                    ),
                ),
            ],
            options={
                "db_table": "wb_sizes",
            },
        ),
    ]
