# Generated by Django 5.2.10 on 2026-05-08 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_wbsizes"),
    ]

    operations = [
        migrations.CreateModel(
            name="WbBarcodes",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("barcode", models.CharField(max_length=100)),
                (
                    "chrt",
                    models.ForeignKey(
                        db_column="chrt_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="barcodes",
                        to="cards.wbsizes",
                    ),
                ),
            ],
            options={
                "db_table": "wb_barcodes",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("barcode", "chrt"), name="wb_barcode_chrt_unique"
                    )
                ],
            },
        ),
    ]
