# Generated by Django 5.2.10 on 2026-05-08 15:24

import cards.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_wbbarcodes"),
        ("contracts", "0020_alter_accuralfn_options_alter_contracts_bs_and_more"),
        ("counterparties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название лота"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание лота"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Лот",
                "verbose_name_plural": "Лоты",
            },
        ),
        migrations.CreateModel(
            name="LotFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=cards.models.lot_file_upload_to, verbose_name="Файл"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название файла"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="cards.lot",
                        verbose_name="Лот",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл лота",
                "verbose_name_plural": "Файлы лота",
            },
        ),
        migrations.CreateModel(
            name="UpdDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=100, verbose_name="Номер УПД")),
                ("date", models.DateField(verbose_name="Дата УПД")),
                ("comment", models.TextField(blank=True)),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upd_documents",
                        to="contracts.contracts",
                        verbose_name="Договор",
                    ),
                ),
                (
                    "counterparty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upd_documents",
                        to="counterparties.counterparty",
                        verbose_name="Поставщик",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upd_documents",
                        to="cards.lot",
                        verbose_name="Лот",
                    ),
                ),
            ],
            options={
                "verbose_name": "УПД",
                "verbose_name_plural": "УПД",
            },
        ),
        migrations.CreateModel(
            name="UpdDocumentFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=cards.models.upd_file_upload_to, verbose_name="Файл"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название файла"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "upd_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="cards.upddocument",
                        verbose_name="УПД",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл УПД",
                "verbose_name_plural": "Файлы УПД",
            },
        ),
    ]
