# Generated by Django 5.2.10 on 2026-05-08 17:06

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_lot_lotfile_upddocument_upddocumentfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="WbProduct",
            fields=[
                (
                    "card",
                    models.OneToOneField(
                        db_column="nm_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="product",
                        serialize=False,
                        to="cards.wbcardraw",
                        verbose_name="Карточка WB",
                    ),
                ),
                ("nm_pid", models.BigIntegerField(blank=True, null=True)),
                ("sa_name", models.CharField(blank=True, max_length=255, null=True)),
                ("sa_pid", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("alternative_name", models.TextField(blank=True, null=True)),
                (
                    "subject_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("brand", models.CharField(blank=True, max_length=255, null=True)),
                ("subject_id", models.BigIntegerField(blank=True, null=True)),
                ("has_parent", models.BooleanField(default=False)),
                ("vat_rate", models.FloatField(blank=True, null=True)),
                ("discount_vat", models.BooleanField(default=False)),
                ("tnved", models.CharField(blank=True, max_length=100, null=True)),
                ("gender", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "origin_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("photo_hq", models.URLField(blank=True, max_length=1000, null=True)),
                ("cert_end_date", models.DateField(blank=True, null=True)),
                ("wb_created_at", models.DateTimeField(blank=True, null=True)),
                ("wb_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "available_sizes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Товар WB",
                "verbose_name_plural": "Товары WB",
                "db_table": "wb_products",
            },
        ),
    ]
