# Generated by Django 5.2.10 on 2026-05-09 07:40

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0005_wbproduct"),
    ]

    operations = [
        migrations.CreateModel(
            name="UPDData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upd_pos",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Позиция УПД"
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Бренд"
                    ),
                ),
                (
                    "upd_sa_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Артикул из УПД",
                    ),
                ),
                (
                    "upd_title",
                    models.TextField(
                        blank=True, null=True, verbose_name="Название из УПД"
                    ),
                ),
                (
                    "proposed_articles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="Предполагаемые артикли",
                    ),
                ),
                (
                    "name_match",
                    models.BooleanField(
                        default=False, verbose_name="Совпадение названия"
                    ),
                ),
                (
                    "upd_size",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Размер из УПД",
                    ),
                ),
                (
                    "available_sizes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="Доступные размеры",
                    ),
                ),
                (
                    "upd_vat_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Ставка НДС в УПД",
                    ),
                ),
                (
                    "card_vat_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Ставка НДС в карточке",
                    ),
                ),
                (
                    "upd_unit",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Ед. изм."
                    ),
                ),
                (
                    "upd_qty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Количество",
                    ),
                ),
                (
                    "upd_price_vatless",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Цена без НДС",
                    ),
                ),
                (
                    "upd_amount_vatless",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Стоимость без НДС",
                    ),
                ),
                (
                    "upd_vat_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="НДС",
                    ),
                ),
                (
                    "upd_amount_vatadd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Стоимость с НДС",
                    ),
                ),
                (
                    "man_cost_per_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Управленческая себестоимость без НДС",
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        choices=[
                            ("RUB", "RUB"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                            ("CHF", "CHF"),
                            ("JPY", "JPY"),
                            ("CNY", "CNY"),
                            ("CAD", "CAD"),
                            ("AUD", "AUD"),
                            ("HKD", "HKD"),
                            ("KZT", "KZT"),
                            ("KGS", "KGS"),
                            ("UZS", "UZS"),
                            ("AZN", "AZN"),
                            ("AMD", "AMD"),
                            ("AED", "AED"),
                        ],
                        default="RUB",
                        max_length=10,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "chrt",
                    models.ForeignKey(
                        blank=True,
                        db_column="chrt_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upd_income_lines",
                        to="cards.wbsizes",
                        verbose_name="Размер WB",
                    ),
                ),
                (
                    "nm",
                    models.ForeignKey(
                        blank=True,
                        db_column="nm_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upd_income_lines",
                        to="cards.wbcardraw",
                        verbose_name="Карточка WB",
                    ),
                ),
                (
                    "upd_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income_lines",
                        to="cards.upddocument",
                        verbose_name="УПД",
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные УПД",
                "verbose_name_plural": "Приходы",
                "db_table": "upd_income_lines",
            },
        ),
    ]
