# Generated by Django 5.2.10 on 2026-05-20 11:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0006_upddata"),
    ]

    operations = [
        migrations.CreateModel(
            name="USK",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sa_name", models.CharField(db_index=True, max_length=100)),
                ("card_id", models.BigIntegerField(db_index=True)),
                ("usk_sa_name", models.CharField(db_index=True, max_length=100)),
                ("usk", models.BigIntegerField(db_index=True)),
                (
                    "upd_sa_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UskUpd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upd_sa_name", models.CharField(db_index=True, max_length=100)),
                ("usk", models.BigIntegerField(db_index=True)),
            ],
        ),
    ]
