# Generated by Django 5.2.10 on 2026-05-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0007_usk_uskupd"),
    ]

    operations = [
        migrations.CreateModel(
            name="WODashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Write Off Dashboard",
                "verbose_name_plural": "Write Off Dashboard",
                "managed": False,
            },
        ),
    ]
