# Generated by Django 5.2.10 on 2026-01-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="brands",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="sales.brand",
                verbose_name="Бренды",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="sales.category",
                verbose_name="Категории",
            ),
        ),
    ]
