# Generated by Django 5.2.10 on 2026-01-25 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_remove_product_brand_remove_product_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(blank=True, null=True)),
                (
                    "basket",
                    models.CharField(
                        blank=True, db_index=True, max_length=5, null=True
                    ),
                ),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.SmallIntegerField(db_index=True, default=0)),
                ("error", models.TextField(blank=True, null=True)),
                (
                    "wb_article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wb_data",
                        to="sales.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные продуктов",
                "verbose_name_plural": "Данные продуктов",
            },
        ),
    ]
