# Generated by Django 5.2.10 on 2026-01-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_productdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="MVSalesProductData",
            fields=[
                (
                    "wb_article_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("status", models.SmallIntegerField(null=True, verbose_name="статус")),
                ("basket", models.TextField(null=True, verbose_name="Корзина WB")),
                (
                    "fetched_at",
                    models.DateTimeField(null=True, verbose_name="Дата загрузки"),
                ),
                ("nm_id", models.TextField(null=True, verbose_name="nm_id")),
                ("imt_id", models.TextField(null=True, verbose_name="WB Артикль")),
                ("imt_name", models.TextField(null=True, verbose_name="Наименование")),
                ("slug", models.TextField(null=True, verbose_name="slug")),
                (
                    "vendor_code",
                    models.TextField(null=True, verbose_name="Код поставщика"),
                ),
                ("subj_name", models.TextField(null=True, verbose_name="Категория")),
                ("subj_root_name", models.TextField(null=True, verbose_name="Группа")),
                ("subject_id", models.TextField(null=True, verbose_name="subject_id")),
                (
                    "subject_root_id",
                    models.TextField(null=True, verbose_name="subject_root_id"),
                ),
                ("brand_name", models.TextField(null=True, verbose_name="Бренд")),
                (
                    "supplier_id",
                    models.TextField(null=True, verbose_name="supplier_id"),
                ),
                (
                    "photo_count",
                    models.SmallIntegerField(null=True, verbose_name="Количество фото"),
                ),
                ("nm_colors_names", models.TextField(null=True, verbose_name="Цвета")),
                (
                    "create_date",
                    models.DateTimeField(null=True, verbose_name="Дата создания"),
                ),
                (
                    "update_date",
                    models.DateTimeField(null=True, verbose_name="Дата обновления"),
                ),
                ("contents", models.TextField(null=True, verbose_name="Кр описание")),
                ("description", models.TextField(null=True, verbose_name="Описание")),
                ("composition", models.TextField(null=True, verbose_name="Состав")),
                (
                    "country",
                    models.TextField(null=True, verbose_name="Страна производитель"),
                ),
                ("sex", models.TextField(null=True, verbose_name="Пол")),
                ("kit", models.TextField(null=True, verbose_name="Комплект")),
            ],
            options={
                "verbose_name": "Номенклатура WB",
                "verbose_name_plural": "Номенклатуры WB",
                "db_table": "mv_sales_productdata",
                "managed": False,
            },
        ),
    ]
