# Generated by Django 5.2.10 on 2026-01-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_mvsalesproductdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=250, verbose_name="Код заказа")),
            ],
            options={
                "verbose_name": "Код заказа",
                "verbose_name_plural": "Коды заказа",
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        db_index=True, max_length=32, unique=True, verbose_name="Размер"
                    ),
                ),
            ],
            options={
                "verbose_name": "Размер",
                "verbose_name_plural": "Размеры",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Наименование")),
            ],
            options={
                "verbose_name": "Склад",
                "verbose_name_plural": "Склады",
            },
        ),
        migrations.RemoveField(
            model_name="barcode",
            name="product",
        ),
        migrations.RemoveField(
            model_name="sellersku",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="barcodes",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="sales.barcode",
                verbose_name="Баркод",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sellersku",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="sales.sellersku",
                verbose_name="Размер",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="sales.size",
                verbose_name="Размер",
            ),
        ),
    ]
