# Generated by Django 5.2.10 on 2026-01-26 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0009_alter_countries_options_and_more"),
        ("sales", "0005_order_size_warehouse_remove_barcode_product_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(verbose_name="Дата создания")),
                ("sale_date", models.DateTimeField(verbose_name="Дата продажи")),
                (
                    "amount_dt",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="dt Выручка"
                    ),
                ),
                (
                    "amount_cr",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="cr Выручка"
                    ),
                ),
                (
                    "quant_dt",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="dt Количество"
                    ),
                ),
                (
                    "quant_cr",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="cr Количество"
                    ),
                ),
                (
                    "dt",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Дт"
                    ),
                ),
                (
                    "cr",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Кр"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(max_length=50, verbose_name="Тип транскации"),
                ),
                (
                    "barcode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sales.barcode",
                        verbose_name="Баркод",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sales.brand",
                        verbose_name="Бренд",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="corporate.countries",
                        verbose_name="Размер",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sales.order",
                        verbose_name="Код заказа",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sales.product",
                        verbose_name="WB Артикль",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sales.size",
                        verbose_name="Размер",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sales.warehouse",
                        verbose_name="Склад",
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные продаж",
                "verbose_name_plural": "Данные продаж",
            },
        ),
    ]
