# Generated by Django 5.2.10 on 2026-01-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_salesdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="MVSalesDaily",
            fields=[
                ("date", models.DateField(primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Оборот",
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Выручка",
                    ),
                ),
                (
                    "comission",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Проц. комисии",
                    ),
                ),
                (
                    "quant",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Количество",
                    ),
                ),
                (
                    "sales",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Продажи",
                    ),
                ),
                (
                    "rtr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Возвраты",
                    ),
                ),
                (
                    "rtr_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="К возвратов",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дневные продажи",
                "verbose_name_plural": "Дневные продажи",
                "db_table": "mv_sales_daily",
                "managed": False,
            },
        ),
    ]
