# Generated by Django 5.2.10 on 2026-02-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_mvdatamartproduct"),
    ]

    operations = [
        migrations.CreateModel(
            name="NMs",
            fields=[
                (
                    "nm_id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, verbose_name="Артикул WB"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "subject",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Категория"
                    ),
                ),
                (
                    "vat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Ставка НДС из карточки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Номенлатура WB_",
                "verbose_name_plural": "Номенлатуры WB_",
            },
        ),
    ]
