# Generated by Django 5.2.10 on 2026-02-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0009_nms"),
    ]

    operations = [
        migrations.CreateModel(
            name="WBDocument",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                (
                    "service_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("creation_time", models.DateTimeField(blank=True, null=True)),
                ("extensions", models.CharField(blank=True, max_length=255, null=True)),
                ("viewed", models.BooleanField(default=False)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Документ WB",
                "verbose_name_plural": "Документы WB",
                "db_table": "wb_raw.wb_documents",
                "managed": False,
            },
        ),
    ]
