# Generated by Django 5.2.10 on 2026-02-25 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_wbdocument'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wbdocument',
            table='"wb_raw"."wb_documents"',
        ),
    ]
